name: Deploy to Cloudflare workers
on:
  workflow_dispatch:
    inputs:
      worker:
        description: 'Name of the worker'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Publish
        run: cd ${{ github.event.inputs.worker }} && npm install && npx --yes wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      # - name: Publish
      #   uses: cloudflare/wrangler-action@2.0.0
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     workingDirectory: ${{ github.event.inputs.worker }}
