name: Deploy (2) to Cloudflare workers
on:
  workflow_dispatch:
    inputs:
      worker:
        description: 'Name of the worker'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: npm install
          workingDirectory: ${{ github.event.inputs.worker }}
